### ISSUE TITLE
Cannot connect to neo4j running on Docker

### ISSUE THREAD

**Issue by balamuru** [neo4j-contrib/mcp-neo4j#42]
## Expected Behavior (Mandatory)
Should be able to connect to neo4j running on docker (same network)

## Actual Behavior (Mandatory)
Errors out

## How to Reproduce the Problem
execute `docker compose up` in directory with the `docker-compose.yml` file with the following contents

```
services:
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/your_password
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
  neo4j-cypher:
    image: mcp/neo4j-cypher:latest
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=your_password
    restart: always
```

Errors
```
neo4j-cypher-1  | Confirming Neo4j is running...
neo4j-cypher-1  | 
neo4j-cypher-1  | Waiting for Neo4j to Start...
neo4j-cypher-1  | 
neo4j-cypher-1  | Traceback (most recent call last):
neo4j-cypher-1  |   File "/usr/local/bin/mcp-neo4j-cypher", line 8, in <module>
neo4j-cypher-1  |     sys.exit(main())
neo4j-cypher-1  |              ^^^^^^
neo4j-cypher-1  |   File "/app/src/mcp_neo4j_cypher/__init__.py", line 17, in main
neo4j-cypher-1  |     asyncio.run(
neo4j-cypher-1  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
neo4j-cypher-1  |     return runner.run(main)
neo4j-cypher-1  |            ^^^^^^^^^^^^^^^^
neo4j-cypher-1  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 89, in run
neo4j-cypher-1  |     raise ValueError("a coroutine was expected, got {!r}".format(coro))
neo4j-cypher-1  | ValueError: a coroutine was expected, got None

```

### Simple Example
* execute the docker compose file above OR
* start neo4j server
* then , execute the following via docker (change creds if needed)
`docker run -e NEO4J_URI=bolt://<host-name>:7687 -e NEO4J_URL=bolt://<host-name>:7687 -e NEO4J_USERNAME=neo4j -e NEO4J_PASSWORD=your_password mcp/neo4j-cypher:latest`

* Note that I defined `NEO4J_URI` and `NEO4J_URL` duplicitously - as a workaround . These need to be consolidated in source code (separate issue)

Datasets and Statements
NA

## Screenshots (where it's possibile)
NA
## Specifications (Mandatory)
NA
Currently used versions

### Versions

  - OS:
  - Library:
  - Neo4j:

**Comment by balamuru** [comment]
I wonder if the choice of protocol has anything to do with the issue I see  , but I'm not sure what the correct config is. For example, we can use bolt or neo4j+s

````
      NEO4J_URL: neo4j+s://neo4j:7687
      NEO4J_URI: bolt://neo4j:7687
```

**Comment by davenovelli** [comment]
Same error

**Comment by nthsense** [comment]
I've been experiencing the same issue and did some local troubleshooting - if it can't connect to the database at all, you should get this error: 
```
failed connection 1 | waiting 4 seconds...
2025-06-05 09:33:15 neo4j-mcp-server-1  | Error: Couldn't connect to {address of your database}
```

When it _can_ connect to the database, I can see that it passes the healthcheck stage, but then you get the `ValueError: a coroutine was expected, got None` message, which on the surface seems to be because server.main() is not async... making that async opens up a can of worms related to asyncio threading though.

**Comment by geso02** [comment]
In docker you need to set the container_name or the hostname field, otherwise the containename is <stackname>-neo4j-1 : 


``` yaml
 neo4j:
    image: neo4j:5.23.0-community-bullseye
    container_name: neo4j
    restart: always
    ports:
      - "7474:7474" # Browser interface
      - "7687:7687" # Bolt protocol
    environment:
      NEO4J_AUTH: none
      NEO4J_dbms_memory_heap_max__size: 8G
      NEO4J_dbms_memory_pagecache_size: 4G
    healthcheck:
      test: ["CMD", "cypher-shell", "RETURN 1"] 
      interval: 30s
      start_period: 8s
      timeout: 10s
      retries: 5
```  

My problem was, that I could not connect to the mcp server, I think SSE is not working properly, so I used supergateway to wrap the stdio calls in SSE:

``` yaml
  supergateway:
    container_name: supergateway-neo4j-proxy
    hostname: supergateway-neo4j-proxy
    build:
      context: . # Sucht nach Dockerfile im aktuellen Verzeichnis
      dockerfile: Dockerfile.supergateway
    ports:
      - "7200:8000"
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: pwd 
      NEO4J_DATABASE: neo4j
      NEO4J_TRANSPORT: stdio
    command: >
      --stdio "uvx mcp-neo4j-cypher"
      --port 8000
      --ssePath /sse
      --messagePath /message
      --baseUrl http://supergateway-neo4j-proxy.de:8000
    depends_on:
      - neo4j 
    restart: unless-stopped

``` 
Dockerfile.supergateway:
``` 

FROM supercorp/supergateway:latest

# Installiere Python und pip für Alpine Linux
RUN apk add --no-cache python3 py3-pip

# Erstelle eine virtuelle Umgebung
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV

# Aktiviere die virtuelle Umgebung (wichtig für nachfolgende RUN-Befehle)
# und füge sie dem PATH hinzu
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Installiere NUR 'uv' und 'mcp-neo4j-cypher' in die virtuelle Umgebung
# Das uvx-Kommando sollte dann durch die mcp-neo4j-cypher Installation bereitgestellt werden.
RUN pip3 install uv mcp-neo4j-cypher

``` 

I was now able to use it in litellm by using the config.yaml: 
``` yaml
mcp_servers:
  neo4j_mcp_server: 
    url: "http://supergateway-neo4j-proxy:8000/sse"
    transport: "sse"
    description: "Neo4j Cypher MCP Server via Supergateway"
    spec_version: "2025-03-26"
``` 


 but to use it in openweb ui I would an openapi.json endpoint but this is not provided.
