### ISSUE TITLE
Cannot connect mcp-neo4j-server to Neo4j database in Docker Compose (persistent localhost connection attempts)

### ISSUE THREAD

**Issue by SaurebhDayaamah** [neo4j-contrib/mcp-neo4j#48]
Hello @jexp , 
Highly appreciate if you could help me here.

## Expected Behavior (Mandatory)
I am expecting to connect mcp-neo4j-server docker container to neo4j docker database instance/container.

## Actual Behavior (Mandatory)
While trying to connect mcp-neo4j-server docker container to neo4j docker database instance/container; it consistently tries to fallback/connect to `localhost:7687` and gets `connection refused.`. I also tried to override it (via `extra_hosts` or network aliases in YAML) but still wasn't able to make `localhost` resolve my Neo4j Container. 

## How to Reproduce the Problem

Docker-Compose.yml

```
services:
  neo4j:
    image: neo4j:${NEO4J_VERSION} # neo4j:5.26.1
    hostname: neo4j-db # Assign a clear hostname for internal network
    ports:
      - "7474:7474" # HTTP port for Neo4j Browser
      - "7687:7687" # Bolt port for applications to connect
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD} # IMPORTANT: Change your_password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.* # For APOC and GDS
    volumes:
      - ./neo4j_data:/data # Persist your Neo4j data
      - ./neo4j_plugins:/plugins # For APOC, GDS, etc.
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474/ || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      my_app_network: # Assign to a custom network
        aliases:
          - neo4j # Standard alias from service name
          - localhost # THIS IS THE CRITICAL ADDITION
  neo4j-mcp:
    image: mcp/neo4j-cypher:latest # Use the correct image if different
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      # Also tried with 'neo4j' as the hostname for the database; instead of localhost
      - NEO4J_URL=bolt://localhost:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD} 
      # - NEO4J_ENCRYPTED=false
      # IMPORTANT: Must match the Neo4j password
      # Add any other environment variables required by mcp-neo4j-server
      # For example, if it needs a specific port to listen on:
      # - MCP_PORT=8080
    #extra_hosts:
     # - host.docker.internal:neo4j
    ports:
      - "8080:8080" # If your mcp-neo4j-server listens on 8080 for external connections
    restart: unless-stopped
    # If you need to map volumes for mcp-neo4j-server (e.g., config files):
    # volumes:
    #   - ./mcp_config:/app/config
    networks:
      - my_app_network # Join the same network
    #entrypoint: /bin/bash -c "echo \"$(getent hosts neo4j | awk '{ print $1 }') localhost\" >> /etc/hosts && exec /usr/local/bin/mcp-neo4j-cypher"

# Docker creates a default network for all services defined here.
# You don't explicitly need to define a 'networks' section unless you
# have specific advanced networking requirements.
# Define the custom network explicitly
networks:
  my_app_network:
    driver: bridge

```
### Simple Example

Here is the log output of `docker compose logs -f` after a clean `docker compose down --volumes --remove-orphans` and `docker compose up -d`

```
neo4j-mcp-1  | Confirming Neo4j is running...

neo4j-mcp-1  | 

neo4j-mcp-1  | Waiting for Neo4j to Start...

neo4j-mcp-1  | 

neo4j-mcp-1  | failed connection 1 | waiting 4 seconds...

neo4j-mcp-1  | Error: Couldn't connect to localhost:7687 (resolved to ('[::1]:7687', '127.0.0.1:7687')):

neo4j-mcp-1  | Failed to establish connection to ResolvedIPv6Address(('::1', 7687, 0, 0)) (reason [Errno 111] Connection refused)

neo4j-mcp-1  | Failed to establish connection to ResolvedIPv4Address(('127.0.0.1', 7687)) (reason [Errno 111] Connection refused)

neo4j-1      | Changed password for user 'neo4j'. IMPORTANT: this change will only take effect if performed before the database is started for the first time.

neo4j-1      | 2025-05-25 12:05:51.071+0000 INFO  Logging config in use: File '/var/lib/neo4j/conf/user-logs.xml'

neo4j-1      | 2025-05-25 12:05:51.077+0000 INFO  Starting...

neo4j-1      | 2025-05-25 12:05:51.506+0000 INFO  This instance is ServerId{be536e21} (be536e21-20a5-4bdb-9233-dec92e37e06c)

neo4j-1      | 2025-05-25 12:05:51.988+0000 INFO  ======== Neo4j 5.26.1 ========

neo4j-1      | 2025-05-25 12:05:52.788+0000 INFO  Anonymous Usage Data is being sent to Neo4j, see https://neo4j.com/docs/usage-data/

neo4j-1      | 2025-05-25 12:05:52.806+0000 INFO  Bolt enabled on [0.0.0.0:7687](http://0.0.0.0:7687/).

neo4j-1      | 2025-05-25 12:05:53.094+0000 INFO  HTTP enabled on [0.0.0.0:7474](http://0.0.0.0:7474/).

neo4j-1      | 2025-05-25 12:05:53.095+0000 INFO  Remote interface available at http://localhost:7474/

neo4j-1      | 2025-05-25 12:05:53.096+0000 INFO  id: DD62EFA3B285BA68DF947817628CB50F50645902DEDE9B324906DB4D3714CBD1

neo4j-1      | 2025-05-25 12:05:53.096+0000 INFO  name: system

neo4j-1      | 2025-05-25 12:05:53.097+0000 INFO  creationDate: 2025-05-25T10:47:17.972Z

neo4j-1      | 2025-05-25 12:05:53.097+0000 INFO  Started.

neo4j-mcp-1  | failed connection 2 | waiting 6 seconds...

neo4j-mcp-1  | Error: Couldn't connect to localhost:7687 (resolved to ('[::1]:7687', '127.0.0.1:7687')):

neo4j-mcp-1  | Failed to establish connection to ResolvedIPv6Address(('::1', 7687, 0, 0)) (reason [Errno 111] Connection refused)

neo4j-mcp-1  | Failed to establish connection to ResolvedIPv4Address(('127.0.0.1', 7687)) (reason [Errno 111] Connection refused)

neo4j-mcp-1  | failed connection 3 | waiting 8 seconds...

neo4j-mcp-1  | Error: Couldn't connect to localhost:7687 (resolved to ('[::1]:7687', '127.0.0.1:7687')):

neo4j-mcp-1  | Failed to establish connection to ResolvedIPv6Address(('::1', 7687, 0, 0)) (reason [Errno 111] Connection refused)

neo4j-mcp-1  | Failed to establish connection to ResolvedIPv4Address(('127.0.0.1', 7687)) (reason [Errno 111] Connection refused)

neo4j-mcp-1  | Traceback (most recent call last):

neo4j-mcp-1  |   File "/usr/local/lib/python3.11/site-packages/neo4j/_async_compat/network/_bolt_socket.py", line 409, in _connect_secure

neo4j-mcp-1  |     s.connect(resolved_address)

neo4j-mcp-1  | ConnectionRefusedError: [Errno 111] Connection refused

neo4j-mcp-1  | 

neo4j-mcp-1  | The above exception was the direct cause of the following exception:

neo4j-mcp-1  | 

neo4j-mcp-1  | Traceback (most recent call last):

neo4j-mcp-1  |   File "/usr/local/lib/python3.11/site-packages/neo4j/_sync/io/_bolt_socket.py", line 328, in connect

neo4j-mcp-1  |     s = cls._connect_secure(

neo4j-mcp-1  |         ^^^^^^^^^^^^^^^^^^^^

neo4j-mcp-1  |   File "/usr/local/lib/python3.11/site-packages/neo4j/_async_compat/network/_bolt_socket.py", line 426, in _connect_secure

neo4j-mcp-1  |     raise ServiceUnavailable(

neo4j-mcp-1  | neo4j.exceptions.ServiceUnavailable: Failed to establish connection to ResolvedIPv6Address(('::1', 7687, 0, 0)) (reason [Errno 111] Connection refused)

neo4j-mcp-1  | 

neo4j-mcp-1  | The above exception was the direct cause of the following exception:

neo4j-mcp-1  | 

neo4j-mcp-1  | Traceback (most recent call last):

neo4j-mcp-1  |   File "/usr/local/bin/mcp-neo4j-cypher", line 8, in <module>

neo4j-mcp-1  |     sys.exit(main())

neo4j-mcp-1  |              ^^^^^^

neo4j-mcp-1  |   File "/app/src/mcp_neo4j_cypher/__init__.py", line 18, in main

neo4j-mcp-1  |     server.main(

neo4j-mcp-1  |   File "/app/src/mcp_neo4j_cypher/server.py", line 193, in main

neo4j-mcp-1  |     healthcheck(db_url, username, password, database)

neo4j-mcp-1  |   File "/app/src/mcp_neo4j_cypher/server.py", line 59, in healthcheck

neo4j-mcp-1  |     raise ex

neo4j-mcp-1  |   File "/app/src/mcp_neo4j_cypher/server.py", line 45, in healthcheck

neo4j-mcp-1  |     session.run("RETURN 1")

neo4j-mcp-1  |   File "/usr/local/lib/python3.11/site-packages/neo4j/_sync/work/session.py", line 313, in run

neo4j-mcp-1  |     self._connect(self._config.default_access_mode)

neo4j-mcp-1  |   File "/usr/local/lib/python3.11/site-packages/neo4j/_sync/work/session.py", line 136, in _connect

neo4j-mcp-1  |     super()._connect(

neo4j-mcp-1  |   File "/usr/local/lib/python3.11/site-packages/neo4j/_sync/work/workspace.py", line 199, in _connect

neo4j-mcp-1  |     self._connection = self._pool.acquire(**acquire_kwargs_)

neo4j-mcp-1  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

neo4j-mcp-1  |   File "/usr/local/lib/python3.11/site-packages/neo4j/_sync/io/_pool.py", line 662, in acquire

neo4j-mcp-1  |     return self._acquire(

neo4j-mcp-1  |            ^^^^^^^^^^^^^^

neo4j-mcp-1  |   File "/usr/local/lib/python3.11/site-packages/neo4j/_sync/io/_pool.py", line 408, in _acquire

neo4j-mcp-1  |     return connection_creator()

neo4j-mcp-1  |            ^^^^^^^^^^^^^^^^^^^^

neo4j-mcp-1  |   File "/usr/local/lib/python3.11/site-packages/neo4j/_sync/io/_pool.py", line 230, in connection_creator

neo4j-mcp-1  |     connection = self.opener(

neo4j-mcp-1  |                  ^^^^^^^^^^^^

neo4j-mcp-1  |   File "/usr/local/lib/python3.11/site-packages/neo4j/_sync/io/_pool.py", line 624, in opener

neo4j-mcp-1  |     return Bolt.open(

neo4j-mcp-1  |            ^^^^^^^^^^

neo4j-mcp-1  |   File "/usr/local/lib/python3.11/site-packages/neo4j/_sync/io/_bolt.py", line 369, in open

neo4j-mcp-1  |     s, protocol_version, handshake, data = BoltSocket.connect(

neo4j-mcp-1  |                                            ^^^^^^^^^^^^^^^^^^^

neo4j-mcp-1  |   File "/usr/local/lib/python3.11/site-packages/neo4j/_sync/io/_bolt_socket.py", line 376, in connect

neo4j-mcp-1  |     raise ServiceUnavailable(

neo4j-mcp-1  | neo4j.exceptions.ServiceUnavailable: Couldn't connect to localhost:7687 (resolved to ('[::1]:7687', '127.0.0.1:7687')):

neo4j-mcp-1  | Failed to establish connection to ResolvedIPv6Address(('::1', 7687, 0, 0)) (reason [Errno 111] Connection refused)

neo4j-mcp-1  | Failed to establish connection to ResolvedIPv4Address(('127.0.0.1', 7687)) (reason [Errno 111] Connection refused)

neo4j-mcp-1 exited with code 0

neo4j-mcp-1  | Confirming Neo4j is running...

neo4j-mcp-1  | 

neo4j-mcp-1  | Waiting for Neo4j to Start...

neo4j-mcp-1  | 

neo4j-mcp-1  | failed connection 1 | waiting 4 seconds...

neo4j-mcp-1  | Error: Couldn't connect to localhost:7687 (resolved to ('[::1]:7687', '127.0.0.1:7687')):

neo4j-mcp-1  | Failed to establish connection to ResolvedIPv6Address(('::1', 7687, 0, 0)) (reason [Errno 111] Connection refused)

neo4j-mcp-1  | Failed to establish connection to ResolvedIPv4Address(('127.0.0.1', 7687)) (reason [Errno 111] Connection refused)

neo4j-mcp-1  | failed connection 2 | waiting 6 seconds...

neo4j-mcp-1  | Error: Couldn't connect to localhost:7687 (resolved to ('[::1]:7687', '127.0.0.1:7687')):

neo4j-mcp-1  | Failed to establish connection to ResolvedIPv6Address(('::1', 7687, 0, 0)) (reason [Errno 111] Connection refused)
```

## Specifications (Mandatory)

- I tried setting `NEO4J_URL=bolt://neo4j:7687` in mcp-neo4j-server environment variables. `docker inspect` confirms this variable is set inside the container.
- Using extra_hosts to map localhost to neo4j's IP (failed with "invalid IP address" due to service name).
- Using a custom Docker network with aliases: - localhost for the neo4j service, and setting `NEO4J_URL=bolt://localhost:7687` for mcp-neo4j-server.
- Attempted a custom entrypoint to modify /etc/hosts directly within the mcp-neo4j-server container at startup to map localhost to neo4j's IP.

In all cases, the mcp-neo4j-server still reports "Couldn't connect to localhost:7687" (resolved to 127.0.0.1 and ::1). The Neo4j container itself starts successfully and reports "Bolt enabled on [0.0.0.0:7687](http://0.0.0.0:7687/)".

This suggests a specific behavior within the mcp-neo4j-server image that prioritizes 127.0.0.1 or ::1 resolution for localhost connections, even when standard Docker networking methods are applied.

### Versions

  - OS: macOS Sequoia  15.5
  - Docker version 28.0.4 
  - Docker compose version v2.34.0-desktop.1
  - Neo4j: 5.26.1

> **Note : I do not want to fork the repository and making a direct change in the python code for some reasons.**
